#!/usr/bin/env python3
"""Fetch Goodreads ratings from book pages (JSON-LD) and write goodreads-ratings.js."""
import urllib.request, json, re, time, os, sys

BOOKS = {
    "evolution":   "https://www.goodreads.com/book/show/241706371",
    "on-vacation": "https://www.goodreads.com/book/show/205491584",
    "the-dream":   "https://www.goodreads.com/book/show/63213444",
}

GR_PAGE_URLS = {
    "evolution":   "https://www.goodreads.com/book/show/241706371-evolution",
    "on-vacation": "https://www.goodreads.com/book/show/205491584-on-vacation",
    "the-dream":   "https://www.goodreads.com/book/show/63213444-the-dream",
}

# Fallback values (updated manually from last known state)
FALLBACK = {
    "evolution":   {"rating": 4.93, "count": 15, "reviews": 10},
    "on-vacation": {"rating": 4.70, "count": 10, "reviews": 0},
    "the-dream":   {"rating": 5.00, "count": 12, "reviews": 0},
}

JSONLD_RE = re.compile(r'<script type="application/ld\+json">(.*?)</script>', re.DOTALL)

def fetch_page(url):
    req = urllib.request.Request(
        url,
        headers={
            "User-Agent": "Mozilla/5.0 (compatible; DanaEnacheBot/1.0; +https://danaenache.com)",
            "Accept": "text/html,application/xhtml+xml",
            "Accept-Language": "en-US,en;q=0.9",
        }
    )
    with urllib.request.urlopen(req, timeout=20) as r:
        return r.read().decode("utf-8", errors="replace")

def extract_rating(html):
    for match in JSONLD_RE.finditer(html):
        try:
            data = json.loads(match.group(1))
            ar = data.get("aggregateRating", {})
            if ar.get("ratingValue") and ar.get("ratingCount"):
                return {
                    "rating":  round(float(ar["ratingValue"]), 2),
                    "count":   int(ar["ratingCount"]),
                    "reviews": int(ar.get("reviewCount", 0)),
                }
        except (json.JSONDecodeError, ValueError, KeyError):
            continue
    return None

def main():
    # Load existing file to preserve values if scraping fails
    existing = dict(FALLBACK)

    ratings = {}
    failed  = []

    for slug, url in BOOKS.items():
        print(f"  Fetching {slug}...", end=" ", flush=True)
        try:
            html   = fetch_page(url)
            result = extract_rating(html)
            if result:
                ratings[slug] = result
                print(f"{result['rating']} ★  ({result['count']} ratings, {result['reviews']} reviews)")
            else:
                raise ValueError("No aggregateRating found in JSON-LD")
        except Exception as ex:
            print(f"FAILED ({ex}) — using fallback")
            ratings[slug] = existing[slug]
            failed.append(slug)
        time.sleep(1.5)  # be polite

    # Write goodreads-ratings.js
    js_data = json.dumps({
        slug: {
            "rating":  r["rating"],
            "count":   r["count"],
            "reviews": r["reviews"],
            "url":     GR_PAGE_URLS[slug],
        }
        for slug, r in ratings.items()
    }, indent=2)

    output = f"""/* Auto-generated by fetch-goodreads.py — do not edit manually */
(function () {{
  var DATA = {js_data};

  function stars(rating) {{
    var pct = (rating / 5) * 100;
    return '<span class="gr-stars" aria-hidden="true">'
      + '<span class="gr-stars-empty">&#9733;&#9733;&#9733;&#9733;&#9733;</span>'
      + '<span class="gr-stars-fill" style="width:' + pct.toFixed(1) + '%">&#9733;&#9733;&#9733;&#9733;&#9733;</span>'
      + '</span>';
  }}

  function render() {{
    document.querySelectorAll('[data-book]').forEach(function (el) {{
      var slug = el.dataset.book;
      var d    = DATA[slug];
      if (!d) return;
      var badge = document.createElement('a');
      badge.href        = d.url;
      badge.target      = '_blank';
      badge.rel         = 'noopener noreferrer';
      badge.className   = 'gr-badge';
      badge.setAttribute('aria-label', d.rating + ' out of 5 stars on Goodreads');
      badge.innerHTML   =
        stars(d.rating) +
        '<span class="gr-score">' + d.rating.toFixed(2) + '</span>' +
        '<span class="gr-logo">Goodreads</span>';
      el.appendChild(badge);
    }});
  }}

  if (document.readyState === 'loading') {{
    document.addEventListener('DOMContentLoaded', render);
  }} else {{
    render();
  }}
}})();
"""

    out_path = os.path.join(os.path.dirname(__file__), "goodreads-ratings.js")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(output)

    print(f"\nWrote goodreads-ratings.js  ({len(failed)} fallback(s))")
    sys.exit(1 if len(failed) == len(BOOKS) else 0)  # fail only if ALL scrapes failed

if __name__ == "__main__":
    main()
